version: 2

defaults: &defaults
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    docker:
      - image: cimg/openjdk:11.0.12

    steps:
      - checkout
      - run: sudo apt install curl 
      - run: curl -fsSL https://deb.nodesource.com/setup_lts.x
      - run: sudo apt-get install -y nodejs
      - run: node -v
      - run: ./build-sbt.sh
      - persist_to_workspace:
          root: ~/repo
          paths: .

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
